name: Workflow CI

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  ArtefactBuilder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci
      
      - name: Run Linter
        run: npm run lint:check
      
      - name: Run audit
        run: npm audit
      
      - name: Build Chrome project
        run: npm run build
      
      - name: Build Firefox project
        run: npm run build:firefox
      
      - name: Archive Chrome artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chromium
          path: ./output/chromium-mv3
      
      - name: Archive Firefox artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: ./output/firefox-mv2-dev



